plugins {
    id 'com.android.application'
}

def carsonVersion = project.hasProperty('CARSONCC_VERSION') ? project.property('CARSONCC_VERSION').toString() : '0.1.0'
def carsonVersionCode = project.hasProperty('CARSONCC_VERSION_CODE') ? project.property('CARSONCC_VERSION_CODE').toString().toInteger() : 1

android {
    namespace 'com.carsoncc.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.carsoncc.mobile'
        minSdk 26
        targetSdk 35
        versionCode carsonVersionCode
        versionName carsonVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
