#include "codegen.h"
#include <stdio.h>
#include <string.h>

typedef struct{FILE*out;const AstNode*function;}Gen;
static int offset_of(const Gen*g,const char*name){int off=-8;for(size_t i=0;i<g->function->parameter_count;i++){if(!strcmp(g->function->parameters[i],name))return 16+(int)(i*8); }for(size_t i=0;i<g->function->child_count;i++){const AstNode*n=g->function->children[i];if(n->kind==AST_LET){if(!strcmp(n->name,name))return off;off-=8;}}return 0;}
static int locals(const AstNode*f){int n=0;for(size_t i=0;i<f->child_count;i++)if(f->children[i]->kind==AST_LET)n++;return n;}
static void expr(Gen*g,const AstNode*n){if(n->kind==AST_INTEGER){fprintf(g->out,"    mov rax, %ld\n",n->integer_value);return;}if(n->kind==AST_VARIABLE){fprintf(g->out,"    mov rax, QWORD PTR [rbp%d]\n",offset_of(g,n->name));return;}if(n->kind==AST_CALL){static const char*regs[]={"rdi","rsi","rdx","rcx","r8","r9"};for(size_t i=n->child_count;i>0;i--){expr(g,n->children[i-1]);fprintf(g->out,"    push rax\n");}for(size_t i=0;i<n->child_count&&i<6;i++)fprintf(g->out,"    pop %s\n",regs[i]);if(n->child_count>6){fprintf(g->out,"    add rsp, %lu\n",(unsigned long)((n->child_count-6)*8));}fprintf(g->out,"    call %s\n",n->name);return;}expr(g,n->left);fprintf(g->out,"    push rax\n");expr(g,n->right);fprintf(g->out,"    mov rcx, rax\n    pop rax\n");switch(n->op){case OP_ADD:fprintf(g->out,"    add rax, rcx\n");break;case OP_SUB:fprintf(g->out,"    sub rax, rcx\n");break;case OP_MUL:fprintf(g->out,"    imul rax, rcx\n");break;case OP_DIV:fprintf(g->out,"    cqo\n    idiv rcx\n");break;}}
static void function_codegen(FILE*out,const AstNode*f){int n=locals(f);int bytes=((n*8+15)/16)*16;Gen g={out,f};fprintf(out,".globl %s\n.type %s, @function\n%s:\n    push rbp\n    mov rbp, rsp\n",f->name,f->name,f->name);if(bytes)fprintf(out,"    sub rsp, %d\n",bytes);static const char*regs[]={"rdi","rsi","rdx","rcx","r8","r9"};for(size_t i=0;i<f->parameter_count;i++){int off=offset_of(&g,f->parameters[i]);if(i<6)fprintf(out,"    mov QWORD PTR [rbp%d], %s\n",off,regs[i]);}for(size_t i=0;i<f->child_count;i++){const AstNode*x=f->children[i];if(x->kind==AST_LET){expr(&g,x->left);fprintf(out,"    mov QWORD PTR [rbp%d], rax\n",offset_of(&g,x->name));}else if(x->kind==AST_RETURN){expr(&g,x->left);fprintf(out,"    leave\n    ret\n");}}fprintf(out,"    xor eax,eax\n    leave\n    ret\n");}
int codegen_x86_64(const AstNode*program,const char*path){FILE*out=fopen(path,"w");if(!out){perror(path);return 0;}fprintf(out,".intel_syntax noprefix\n.text\n");for(size_t i=0;i<program->child_count;i++)function_codegen(out,program->children[i]);fclose(out);return 1;}
